<?php

namespace Carlohcs\Core\Models\Avatar;

use Carlohcs\Core\Models\AbstractModel;

/**
 * AvatarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvatarRepository extends AbstractModel
{
	/**
	 * Save a avatar
	 * 
	 * @param  array $data
	 * @return object $avatar
	 */
	public function save($data)
	{
		$coreBaseName = $this->getCoreBaseName();

		//Get account
		$account = $this->getEntityRepository($coreBaseName.'Account\AccountModel')->get($data['accountId']);
		
		$avatar = $account->getAvatar();

		if(!$avatar)
		{
			$avatar = $this->getNewEntityRepository();
		}

		//Set the avatar
		$avatar->setAvatar($data['avatar']);

		//Set the thumbnail
		$avatar->setThumbnail($data['thumbnail']);

		// ==================================================================
		//
		// Relationships
		//
		// ------------------------------------------------------------------
		
		$avatar->setAccount($account);
		
		//The correct be, but, doesn't work
		//$account->setAvatar($avatar);
		//$save = $this->saveEntity($account);

		$save = $this->saveEntity($avatar);
		
		return $save;
	}
}
