<?php

namespace Core\Models\Address\State;

use Core\Models\AbstractModel;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends AbstractModel
{
}
