<?php

namespace Carlohcs\Core\Models\Address\City;

use Carlohcs\Core\Models\AbstractModel;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends AbstractModel
{

	/**
	 * Return cities from a determinate state
	 * 
	 * @param  integer $id
	 * @return object $data
	 */
	public function getCitiesFromState($stateId)
	{
		$data = $this->getEntityRepository()
		->findBy([
			'stateId' => $stateId
		]);

	   return $data;
	}

	/**
	 * Return a array('id' => 'cityId', 'city' => 'Name city') cities from a determinate state
	 * 
	 * @param  integer $id
	 * @return object $data
	 */
	public function getArrayCitiesFromState($stateId)
	{
		$data = $this->getCitiesFromState($stateId);

		$cities = array_reduce($data, function($newArray, $city){
            $newArray[] = [
                'id' => $city->getId(),
                'city' => $city->getCity()
            ];
            return $newArray;
        });

	   return $cities;
	}
}
