<?php

namespace Core\Models\Telephone;

use Core\Models\AbstractModel;

/**
 * TelephoneTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelephoneTypeRepository extends AbstractModel
{
}
