<?php

namespace Carlohcs\Core\Models\Account;

use Carlohcs\Core\Models\AbstractModel;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends AbstractModel
{
	/**
	 * Get a account by login
	 * 
	 * @param  string  $login
	 * @param  boolean $active
	 * @return object $account
	 */
	public function getByLogin($login, $active = true)
	{
		$account = $this->getEntityRepository()
		->findOneBy([
			'login' => $login,
			'active' => $active
		]);

		return $account;
	}
}
