<?php

namespace Core\Models\Email;

use Core\Models\AbstractModel;

/**
 * EmailTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTypeRepository extends AbstractModel
{
}
