<?php

namespace Core\Models\Email;

use Core\Models\AbstractModel;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends AbstractModel
{
}
