<?php

namespace Carlohcs\Core\Models\Address;

use Carlohcs\Core\Models\AbstractModel;
use Carlohcs\Core\Models\Account\AccountModel;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends AbstractModel
{
	/**
	 * Save the a AddressRepository
	 * 
	 * @param  array $data
	 * @return object $save
	 */
	public function save($data)
	{
		//Get a entity persist object
		$repository = $this->getEntityPersistObject($data);

		//Set the cep
		$repository->setCep($data['cep']);
		
		//Set the patio
		$repository->setPatio($data['patio']);

		//Set the number
		$repository->setNumber($data['number']);

		//Set the complement
		if(isset($data['complement']) && !empty(trim($data['complement'])))
		{
			$repository->setComplement($data['complement']);
		}

		//Set the neighborhood
		$repository->setNeighborhood($data['neighborhood']);

		// ==================================================================
		//
		// Relationships
		//
		// ------------------------------------------------------------------
		
		$coreBaseName = $this->getCoreBaseName();

		//Account
		$accountModel = $this->getEntityRepository($coreBaseName.'Account\AccountModel')->get($data['accountId']);
		$repository->setAccount($accountModel);

		//State
		$stateModel = $this->getEntityRepository($coreBaseName.'Address\State\StateModel')->get($data['stateId']);
		$repository->setState($stateModel);

		//City
		$citytModel = $this->getEntityRepository($coreBaseName.'Address\City\CityModel')->get($data['cityId']);
		$repository->setCity($citytModel);

		//Save
		$save = $this->saveEntity($repository);

		return $save;
	}
}
